import json

x = {
    "result": "{\"schema\":{\"fields\":[{\"kind\":\"dimension\",\"name\":\"Store Name\",\"type\":{\"kind\":\"string_type\"},\"annotations\":[{\"value\":\"#(malloy) reference_id = \\\"d30db42d-d588-4f30-aaec-008f8ec4055d\\\" drill_expression { kind = field_reference name = \\\"Store Name\\\" path = [orders, stores] code = name }\\n\"}]},{\"kind\":\"dimension\",\"name\":\"Total Quantity\",\"type\":{\"kind\":\"number_type\",\"subtype\":\"integer\"},\"annotations\":[{\"value\":\"#(malloy) reference_id = \\\"a3fdca57-a5c9-496a-9305-0aee93b7ea79\\\" calculation drill_expression { kind = field_reference name = \\\"Total Quantity\\\" }\\n\"}]},{\"kind\":\"dimension\",\"name\":\"Total Revenue\",\"type\":{\"kind\":\"number_type\",\"subtype\":\"decimal\"},\"annotations\":[{\"value\":\"#(malloy) reference_id = \\\"1be64420-26f0-45a0-a1b0-7e6d1e1cfdf2\\\" calculation drill_expression { kind = field_reference name = \\\"Total Revenue\\\" }\\n\"}]}]},\"data\":{\"kind\":\"array_cell\",\"array_value\":[{\"kind\":\"record_cell\",\"record_value\":[{\"kind\":\"string_cell\",\"string_value\":\"West End Branch\"},{\"kind\":\"number_cell\",\"number_value\":12651,\"subtype\":\"integer\"},{\"kind\":\"number_cell\",\"number_value\":3645276.72,\"subtype\":\"decimal\"}]},{\"kind\":\"record_cell\",\"record_value\":[{\"kind\":\"string_cell\",\"string_value\":\"Euro Hub Logistics\"},{\"kind\":\"number_cell\",\"number_value\":12517,\"subtype\":\"integer\"},{\"kind\":\"number_cell\",\"number_value\":3569000.98,\"subtype\":\"decimal\"}]},{\"kind\":\"record_cell\",\"record_value\":[{\"kind\":\"string_cell\",\"string_value\":\"Downtown flagship\"},{\"kind\":\"number_cell\",\"number_value\":12376,\"subtype\":\"integer\"},{\"kind\":\"number_cell\",\"number_value\":3673139.62,\"subtype\":\"decimal\"}]},{\"kind\":\"record_cell\",\"record_value\":[{\"kind\":\"string_cell\",\"string_value\":\"Metro Mall Outlet\"},{\"kind\":\"number_cell\",\"number_value\":12198,\"subtype\":\"integer\"},{\"kind\":\"number_cell\",\"number_value\":3530353.73,\"subtype\":\"decimal\"}]}]},\"connection_name\":\"test_db\",\"annotations\":[{\"value\":\"#(malloy) drillable ordered_by = [{ `Total Quantity` = desc }]\\n\"},{\"value\":\"#(malloy) source.name = order_items\\n\"},{\"value\":\"#(malloy) query_name = __stage0\\n\"}],\"sql\":\"WITH __stage0 AS (\\n  SELECT \\n     stores_0.\\\"name\\\" as \\\"Store Name\\\",\\n     COALESCE(SUM(base.\\\"quantity\\\"),0) as \\\"Total Quantity\\\",\\n     COALESCE(SUM(base.\\\"quantity\\\"*base.\\\"unit_price\\\"),0) as \\\"Total Revenue\\\"\\n  FROM public.order_items as base\\n   LEFT JOIN public.orders AS orders_0\\n    ON base.\\\"order_id\\\"=orders_0.\\\"id\\\"\\n   LEFT JOIN public.stores AS stores_0\\n    ON orders_0.\\\"store_id\\\"=stores_0.\\\"id\\\"\\n  GROUP BY 1\\n  ORDER BY 2 desc NULLS LAST\\n)\\nSELECT row_to_json(finalStage) as row FROM __stage0 AS finalStage\"}",
    "resource": "/api/v0/environments/test/packages/model_a/models/model_a.malloy/query"
}


result = json.loads(x["result"])

with open("C:/dev/chester-bi/.tests/result.json", "w" , encoding="utf-8") as f:
    json.dump(result, f)