import { DATE_TIME_FORMAT_OPTIONS } from "../../lib/dateTimeFormat";

export const CardSchema= {
    chartType: "card",
    fields: [
        {
            name: "title",
            inputType : "text",
            label : "Title",
            placeholder : "Enter title",
            required : false,
        }
        ,
        {
            name : "titleFontSize",
            inputType : "number",
            label : "Title Font Size",
            placeholder : "Enter title font size",
            required : false,
        },
        {
            name : "titleFontColor",
            inputType : "color",
            label : "Title Font Color",
            placeholder : "Enter title font color",
            required : false,
        },
        {
            name : "value",
            inputType : "select",
            label : "Value",
            placeholder : "Enter value",
            required : true,
        },
        {
            name : "valueFontSize",
            inputType : "number",
            label : "Value Font Size",
            placeholder : "Enter value font size",
            required : false,
        },
        {
            name : "valueFontColor",
            inputType : "color",
            label : "Value Font Color",
            placeholder : "Enter value font color",
            required : false,
        },
        {
            name : "valueFormat",
            inputType : "select",
            label : "Value Format",
            placeholder : "Select value format",
            required : false,
        },
        {
            name : "hasTarget",
            inputType : "switch",
            label : "Has Target",
            placeholder : "Has target",
            required : false,
            defaultValue : "false",
        },
        {
            name : "target",
            inputType : "text",
            label : "Target",
            placeholder : "Enter target",
            required : false,
            showWhen : "hasTarget",
        },
        {
            name : "targetFormat",
            inputType : "select",
            label : "Target Format",
            placeholder : "Select target format",
            required : false,
            showWhen : "hasTarget",
        },
        {
            name : "targetBarColor",
            inputType : "color",
            label : "Target Bar Color",
            placeholder : "Enter target bar color",
            required : false,
            showWhen : "hasTarget",
        },
        {
            name: "hasCompare",
            inputType: "switch",
            label: "Show Comparison",
            required: false,
            defaultValue: "false",
        },
        {
            name: "compareField",
            inputType: "select",
            label: "Compare Field",
            placeholder: "Select field to compare against",
            required: false,
            showWhen: "hasCompare",
        },
        {
            name: "compareLabel",
            inputType: "text",
            label: "Compare Label",
            placeholder: "e.g. vs Last Period",
            required: false,
            showWhen: "hasCompare",
        },
        {
            name: "compareFormat",
            inputType: "select",
            label: "Compare Format",
            placeholder: "Select compare format",
            required: false,
            showWhen: "hasCompare",
        },
    ]
}

export const LineChartSchema= {
    chartType: "line",
    fields: [
        {
            name: "title",
            inputType : "text",
            label : "Title",
            placeholder : "Enter title",
            required : false,
        },
        {
            name: "titleFontSize",
            inputType : "number",
            label : "Title Font Size",
            placeholder : "Enter title font size",
            required : false,
        },
        {
            name: "titleFontColor",
            inputType : "color",
            label : "Title Font Color",
            placeholder : "Enter title font color",
            required : false,
        }
        ,
        {
            name : "lineType",
            inputType : "select",
            label : "Line Type",
            placeholder : "Select line type",
            required : false,
            options : [
                { value: "smooth", label: "Smooth" },
                { value: "straight", label: "Straight" },


            ],
        },
        {
            name: "xAxis",
            inputType : "select",
            label : "X Axis",
            placeholder : "Enter x axis",
            required : true,
        },
        {
            name: "format",
            inputType: "select",
            label: "Format",
            placeholder: "Select format",
            required: false,
            options: DATE_TIME_FORMAT_OPTIONS,
        },
        {
            name:"xAxisColor",
            inputType : "color",
            label : "X Axis Color",
            placeholder : "Enter x axis color",
            required : false,
        },
        
        {
            name: "yAxis",
            inputType : "multi-select",
            label : "Y Axis",
            placeholder : "Enter y axis",
            required : true,
        },
        {
            name: "showDataPoints",
            inputType: "switch",
            label: "Show Data Points",
            placeholder: "Show data points",
            required: false,
            defaultValue: "false",
        },
        {
            name: "yAxisColor",
            inputType : "multi-color",
            label : "Y Axis Color",
            placeholder : "Enter y axis color",
            required : false,
        },
        {
            name: "yAxisFormat",
            inputType: "select",
            label: "Y Axis Format",
            placeholder: "Select Y axis format",
            required: false,
            options: [
                { value: "currency", label: "Currency" },
                { value: "number", label: "Number" },
                { value: "decimal", label: "Decimal" },
            ],
        },
        {
            name : "legend",
            inputType : "multi-text",
            label : "Legend",
            placeholder : "Enter legend",
            required : false,
        },

    ]
}

export const BarChartSchema = {
    chartType: "bar",
    fields: [
        {
            name: "title",
            inputType: "text",
            label: "Title",
            placeholder: "Enter title",
            required: false,
        },
        {
            name: "titleFontSize",
            inputType: "number",
            label: "Title Font Size",
            placeholder: "Enter title font size",
            required: false,
        },
        {
            name: "titleFontColor",
            inputType: "color",
            label: "Title Font Color",
            placeholder: "Enter title font color",
            required: false,
        },
        {
            name: "barOrientation",
            inputType: "select",
            label: "Orientation",
            placeholder: "Select orientation",
            required: false,
            defaultValue: "vertical",
            options: [
                { value: "vertical", label: "Vertical" },
                { value: "horizontal", label: "Horizontal" },
            ],
        },
        {
            name: "stacked",
            inputType: "switch",
            label: "Stacked",
            placeholder: "Stack series",
            required: false,
            defaultValue: "false",
        },
        {
            name: "xAxis",
            inputType: "select",
            label: "X Axis",
            placeholder: "Enter x axis",
            required: true,
        },
        {
            name: "xAxisColor",
            inputType: "color",
            label: "X Axis Color",
            placeholder: "Enter x axis color",
            required: false,
        },
        {
            name: "yAxis",
            inputType: "multi-select",
            label: "Y Axis",
            placeholder: "Enter y axis",
            required: true,
        },
        {
            name: "yAxisColor",
            inputType: "multi-color",
            label: "Y Axis Color",
            placeholder: "Enter y axis color",
            required: false,
        },
        {
            name: "legend",
            inputType: "multi-text",
            label: "Legend",
            placeholder: "Enter legend",
            required: false,
        },
         ],
};


export const PieChartSchema = {
    chartType: "pie",
    fields: [
        {
            name: "title",
            inputType: "text",
            label: "Title",
            placeholder: "Enter title",
            required: false,
        },
        {
            name: "titleFontSize",
            inputType: "number",
            label: "Title Font Size",
            placeholder: "Enter title font size",
            required: false,
        },
        {
            name: "titleFontColor",
            inputType: "color",
            label: "Title Font Color",
            placeholder: "Enter title font color",
            required: false,
        },
        {
            name: "category",
            inputType: "select",
            label: "Category",
            placeholder: "Select category field",
            required: true,
        },
        {
            name: "value",
            inputType: "select",
            label: "Value",
            placeholder: "Select value field",
            required: true,
        },
        {
            name: "sliceColor",
            inputType: "multi-color",
            label: "Slice Colors",
            placeholder: "Enter slice colors",
            required: false,
        },
        {
            name: "legend",
            inputType: "multi-text",
            label: "Legend",
            placeholder: "Enter legend labels",
            required: false,
        },
        {
            name: "radius",
            inputType: "number",
            label: "Inner Radius (%)",
            placeholder: "0 for pie, >0 for donut",
            defaultValue: "0",
            required: false,
        },
        {
            name: "showValue",
            inputType: "switch",
            label: "Show Value",
            placeholder: "Show actual value on slices",
            required: false,
            defaultValue: "false",
        },
        {
            name: "showPercentage",
            inputType: "switch",
            label: "Show Percentage",
            placeholder: "Show percentage on slices",
            required: false,
            defaultValue: "false",
        },
        {
            name : "valuePosition",
            inputType: "select",
            label: "Value Position",
            placeholder: "Select value position",
            required: false,
            defaultValue: "inside",
            options: [
                { value: "inside", label: "Inside" },
                { value: "outside", label: "Outside" },
                { value: "center", label: "Center" },
                { value : "left", label: "Left" },
                { value : "right", label: "Right" },
            ],
        }
    ],
};

export const TableChartSchema = {
    chartType: "table",
    fields: [
        {
            name: "title",
            inputType: "text",
            label: "Title",
            placeholder: "Enter title",
            required: false,
        },
        {
            name: "titleFontSize",
            inputType: "number",
            label: "Title Font Size",
            placeholder: "14",
            required: false,
        },
        {
            name: "titleFontColor",
            inputType: "color",
            label: "Title Font Color",
            required: false,
        },
        {
            name: "columns",
            inputType: "multi-select",
            label: "Columns",
            placeholder: "Select columns to display (all if empty)",
            required: false,
        },
        {
            name: "pageSize",
            inputType: "select",
            label: "Rows per page",
            required: false,
            defaultValue: "10",
            options: [
                { value: "5", label: "5" },
                { value: "10", label: "10" },
                { value: "20", label: "20" },
                { value: "50", label: "50" },
                { value: "100", label: "100" },
            ],
        },
        {
            name: "striped",
            inputType: "switch",
            label: "Striped rows",
            defaultValue: "true",
            required: false,
        },
        {
            name: "showIndex",
            inputType: "switch",
            label: "Show row numbers",
            defaultValue: "false",
            required: false,
        },
    ],
};

export const WaterFallChartSchema = {
    chartType: "waterfall",
    fields: [
        {
            name: "title",
            inputType: "text",
            label: "Title",
            placeholder: "Enter title",
            required: false,
        },
        {
            name: "titleFontSize",
            inputType: "number",
            label: "Title Font Size",
            placeholder: "Enter title font size",
            required: false,
        },
        {
            name: "titleFontColor",
            inputType: "color",
            label: "Title Font Color",
            placeholder: "Enter title font color",
            required: false,
        },
        {
            name: "xAxis",
            inputType: "select",
            label: "X Axis",
            placeholder: "Select category field",
            required: true,
        },
        {
            name: "xAxisColor",
            inputType: "color",
            label: "X Axis Color",
            placeholder: "Enter x axis color",
            required: false,
        },
        {
            name: "format",
            inputType: "select",
            label: "Format",
            placeholder: "Select format",
            required: false,
            options: DATE_TIME_FORMAT_OPTIONS,
        },
        {
            name: "value",
            inputType: "select",
            label: "Value",
            placeholder: "Select amount field (+/- delta per category)",
            required: true,
        },
        {
            name: "valueFormat",
            inputType: "select",
            label: "Value Format",
            placeholder: "Select value format",
            required: false,
            options: [
                { value: "currency", label: "Currency" },
                { value: "number", label: "Number" },
                { value: "decimal", label: "Decimal" },
            ],
        },
        {
            name: "increaseColor",
            inputType: "color",
            label: "Increase Color",
            placeholder: "Enter increase color",
            required: false,
            defaultValue: "#10b981",
        },
        {
            name: "decreaseColor",
            inputType: "color",
            label: "Decrease Color",
            placeholder: "Enter decrease color",
            required: false,
            defaultValue: "#ef4444",
        },
        {
            name: "showConnectors",
            inputType: "switch",
            label: "Show Connectors",
            placeholder: "Show connector lines between bars",
            required: false,
            defaultValue: "true",
        },
        {
            name: "showValue",
            inputType: "switch",
            label: "Show Value",
            placeholder: "Show value labels on bars",
            required: false,
            defaultValue: "false",
        },
        {
            name: "legend",
            inputType: "multi-text",
            label: "Legend",
            placeholder: "Labels for Increase, Decrease",
            required: false,
        },
    ],
};